#setting up directories
gfsDir = '/media/AGFORTELNY/PROJECTS/Gratz_InflammedSkin'
rawDir = f'{gfsDir}/raw_data/scRNA_from_BSF/COUNT'
plotsDir = f'{gfsDir}/plots'
tablesDir = f'{gfsDir}/tables'
dataDir = 'data'
resDir = 'results'
funDir = 'functions'
vDir = '/vscratch/scRNAseq'
